export { default as perfora } from './perfora.svg'
export { default as caretUpDown } from './caretupdown.svg'
export { default as caretDown } from './caretdown.svg'
export { default as chevronDouble } from './chevrondouble.svg'
export { default as plus } from './plus.svg'
export { default as mama } from './mama.svg'
export { default as mid } from './mid.svg'
export { default as home } from './home.svg'
export { default as users } from './users.svg'
export { default as default } from './default.svg'
export { default as creative } from './creative.svg'
export { default as  help} from './help.svg'
export { default as  setting} from './settings.svg'
export { default as chevrondownwhite } from './chevrondownwhite.svg'
export { default as bi_toogle } from './bitoogle.svg'
export { default as chartline } from './chartline.svg'
export { default as calender } from './calendar.svg'
export { default as blinkit } from './blinkit.svg'
export { default as zepto } from './zepto.svg'
export { default as instamart } from './instamart.svg'
export { default as arrowUp } from './arrowup.svg'
export { default as arrowDown } from './arrowdown.svg'
